config/routes.rb
Rails.application.routes.draw do
  get 'tasks_imports/new'
  get 'tasks_imports/create'
  get 'tasks_import/new'
  get 'tasks_import/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  # PAGES GETS
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :tasks_imports, only: [:new, :create]


  # READ ALL
  get 'tasks', to: 'tasks#index'
  # POST the form
  post 'tasks', to: 'tasks#create'

  # For the CREATE route, we need to do a NEW route, which needs to come before SHOW
  get 'tasks/new', to: 'tasks#new'
  # GET with pre-filled attributes for editing
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'

  # READ ONE
  get 'tasks/:id', to: 'tasks#show', as: :task

  # PATCH the form
  patch 'tasks/:id', to: 'tasks#update'
  
  # DELETE
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates_presence_of :title
end

app/models/tasks_import.rb
class TasksImport
    include ActiveModel::Model
    require 'roo'
  
    attr_accessor :file
  
    def initialize(attributes={})
      attributes.each { |title, details| send("#{title}=", details) }
    end
  
    def persisted?
      false
    end
  
    # Case statement to open spreadsheet using Roo.
    def open_spreadsheet
      case File.extname(file.original_filename)
        # Use native CSV tools in case of that type of file
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end
  
    def load_imported_items
      spreadsheet = open_spreadsheet
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).map do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        task = Task.find_by_id(row["id"]) || Task.new
        task.attributes = row.to_hash
        task
      end
    end
  
    def imported_items
      @imported_items ||= load_imported_items
    end
  
    def save
      if imported_items.map(&:valid?).all?
        imported_items.each(&:save!)
        true
      else
        imported_items.each_with_index do |item, index|
          item.errors.full_messages.each do |msg|
            errors.add :base, "Row #{index + 6}: #{msg}"
          end
        end
        false
      end
    end
  
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end

    def contact
    end

    def home
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
    end

    def new
        # To instantiate the form_for
        @task = Task.new
    end

    def show
        @task = Task.find(params[:id])
    end

    def create
        # We need strong params to save data
        @task = Task.new(task_params)
        @task.save

        redirect_to task_path(@task)
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        @task.update(task_params)

        redirect_to task_path(@task)
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy

        redirect_to tasks_path
    end

    private

    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end
end

app/controllers/tasks_imports_controller.rb
class TasksImportsController < ApplicationController
  def new
    @tasks_import = TasksImport.new
  end

  def create
    @tasks_import = TasksImport.new(params[:tasks_import])
    if @tasks_import.save
      redirect_to tasks_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tasks_import_helper.rb
module TasksImportHelper
end

app/helpers/tasks_imports_helper.rb
module TasksImportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Il-Qoffa</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="main">
          <div class="card">
          <%= render 'shared/navbar'  %>
            <%= yield %>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Dwar il-Qoffa 🧺</h1>
<p>Il-Qoffa huwa spirat mill-listi tax-xiri li kienet thalli fuq il-mejda ta' barra in-Nanna tieghi. Minnhom kont nilmah il-hsibijiet taghha, il-twehdin fuq it-tfal u l-familja taghha u ma jonqosx, dejjem l-imhabba ghall-ikel bnin mediterran u tradizzjonali. Dejjem kilna bnin u tajjeb, u ta' dan nizzik hajr lilha. Dan l-app huwa omagg ghalik, Nan!</p>

app/views/pages/contact.html.erb
<h1>Ikkuntatjana</h1>
<p>Ibghatilna messagg u ghidilna x'tahseb fuq dan l-app.</p>

app/views/pages/home.html.erb
<h1>Il-Qoffa 🧺</h1>
<p>Il-lista ghax-xirja tieghek, issa bil-Malti biss!</p>
<div class="flex">
    <div class="btn"><%= link_to (image_tag('glasses-outline.svg')), tasks_path %></div>
    <div class="btn"><%= link_to (image_tag('add-circle-outline.svg')), tasks_new_path %></div>
    <div class="btn"><%= link_to (image_tag('cloud-upload-outline.svg')), new_tasks_import_path %></div>
</div>
       

app/views/shared/_navbar.html.erb
<div class="container">
    <p>Illum, <span><%= Time.now.strftime("%A")%></span>. Il-hin issa huwa <span><%= Time.now.strftime("%k : %M")%></span></p>
    <div class="info-btn">
        <%= link_to (image_tag('home-outline.svg')), root_path %>
        <%= link_to (image_tag('information-circle-outline.svg')), about_path %>
    </div>
</div>

app/views/tasks/edit.html.erb
<h1>Biddel xi haga</h1>
<div class="form">
    <%= form_for(@task) do |t| %>
        <%= t.label :Haga %>
        <%= t.text_field :title %>
        <%= t.label :Dettalji %>
        <%= t.text_field :details %>
        <%= t.label :Lesta %>
        <%= t.check_box :completed %>
        <%= t.submit %>
    <% end %>
</div>

app/views/tasks/index.html.erb
<h1>Bhalissa fil-qoffa ghandek:</h1>
<%= link_to (image_tag('add-circle-outline.svg')), tasks_new_path %>
<ul>
    <% @tasks.each do |t| %>
    <% if t.completed %>
        <li class="flex">
            <%= link_to t.title, task_path(t), {:class => 'striken'}%> 
            <%= link_to (image_tag('pencil-outline.svg')), task_path(t) %>
                <%= link_to (image_tag('trash-outline.svg')), 
                t,
                method: :delete,
                data: { confirm: "Inti zgur trid tnehhiha?" }
                %>  
        </li>
    <% else %>
        <li class="flex">
            <%= link_to t.title, task_path(t) %> 
            <%= link_to (image_tag('pencil-outline.svg')), task_path(t) %>
                <%= link_to (image_tag('trash-outline.svg')), 
                t,
                method: :delete,
                data: { confirm: "Inti zgur trid tnehhiha?" }
                %>  
        </li>
        <% end %>
    <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Zid xi haga</h1>
<div class="form">
    <%= form_for(@task) do |t| %>
        <%= t.label :Haga %>
        <%= t.text_field :title %>
        <%= t.label :Dettalji %>
        <%= t.text_field :details %>
        <%= t.label :Lesta %>
        <%= t.check_box :completed %>
        <%= t.submit %>
    <% end %>
</div>

app/views/tasks/show.html.erb
<h1>Dettalji tal-affarijiet</h1>
<div class="flex">
    <h2><%= @task.title  %></h2>
    <%= link_to (image_tag('pencil-outline.svg')), edit_task_path %>
</div>
<h3>Kemm ghandi bzonn nixtri:</h3>
<p><%= @task.details %></p>

<%= link_to (image_tag('arrow-back-circle-outline.svg')), tasks_path %>

app/views/tasks_imports/create.html.erb
<h1>TasksImports#create</h1>
<p>Find me in app/views/tasks_imports/create.html.erb</p>

app/views/tasks_imports/new.html.erb
<h1>Tella' lista minn dok pdf</h1>

<%= form_for @tasks_import do |f| %>
  <% if @tasks_import.errors.any? %>
    <%= pluralize(@tasks_import.errors.count, "error") %> prevented us from
    importing your spreadsheet. Please update your spreadsheet and try agin.
    <ul>
      <% @tasks_import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.file_field :file %>
  <%= f.submit "Import File" %>
<% end %>